services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - '4000:3000'
    env_file: .env
    depends_on:
      - db
    restart: always
    networks:
      - internal

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - '8081:80'
    restart: always
    networks:
      - external

  db:
    container_name: postgres
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - internal

  adminer:
    image: adminer
    ports:
      - '8082:8080'
    depends_on:
      - db
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
  external: